services:
  mariadb:
    image: mariadb
    build: ./requirements/mariadb
    env_file: .env
    volumes:
      - DB:/database
    networks:
      - mynetwork
    expose:
      - "3306"
  wordpress:
    image: wordpress
    build: ./requirements/wordpress
    env_file: .env
    volumes:
      - wordpress_files:/www
    networks:
      - mynetwork
    expose:
      - "9000"
      - "3306"
  nginx:
    image: nginx
    build: ./requirements/nginx
    env_file: .env
    volumes:
      - wordpress_files:/www
    networks:
      - mynetwork
    expose:
      - "9000"
    ports:
      - "80:80"
      - "443:443"
volumes:
  DB:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/gcorreia/data/DB/
  wordpress_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/gcorreia/data/wordpress_files/
networks:
  mynetwork:
